export const SET_USER = "SET_USER";

export const itemActions = {
    ITEMS_FETCHING: "ITEMS_FETCHING",
    ITEMS_FETCHED: "ITEMS_FETCHED",
    FETCH_FAILED: "FETCH_FAILED",
};
export const serviceActions = {
    SERVICES_FETCHING: "SERVICES_FETCHING",
    SERVICES_FETCHED: "SERVICES_FETCHED",
    FETCH_FAILED: "FETCH_FAILED",
};
export const providerActions = {
    PROVIDERS_FETCHING: "PROVIDERS_FETCHING",
    PROVIDERS_FETCHED: "PROVIDERS_FETCHED",
    PROVIDERS_CREATING: "PROVIDERS_CREATING",
    PROVIDERS_CREATED: "PROVIDERS_CREATED",
    SET_NEW_PROVIDER: "SET_NEW_PROVIDER",
    FETCH_FAILED: "FETCH_FAILED",
};
